services:
  containers_back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containers_back
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
